services:
  computer-use-demo:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /home/computeruse/entrypoint.sh
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "5900:5900"
      - "6080:6080"
      - "8501:8501"
      - "5678:5678"
      - "5679:5679"
    volumes: []
      # uncomment bewlow below if you wanna mount the local files to the container for debugging purposes
      # - ./computer_use_demo:/home/computeruse/computer_use_demo/
      # - ./image/entrypoint.sh:/home/computeruse/entrypoint.sh
      # Alternatively you can mount specific modules to `/home/computeruse/.venv/lib/python3.11/site-packages/<module_name>`
    environment:
      - ENABLE_DEBUGPY=1
